# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sfft_gui.ui'
#
# Created: Sun Dec 14 21:56:17 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(921, 656)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(261, 202))
        self.groupBox.setMaximumSize(QtCore.QSize(261, 301))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.downsample_fac = QtGui.QLineEdit(self.groupBox)
        self.downsample_fac.setObjectName("downsample_fac")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.downsample_fac)
        self.fft_size = QtGui.QLineEdit(self.groupBox)
        self.fft_size.setMinimumSize(QtCore.QSize(0, 0))
        self.fft_size.setObjectName("fft_size")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.fft_size)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.overlap_fac = QtGui.QLineEdit(self.groupBox)
        self.overlap_fac.setObjectName("overlap_fac")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.overlap_fac)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clip_min = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clip_min.sizePolicy().hasHeightForWidth())
        self.clip_min.setSizePolicy(sizePolicy)
        self.clip_min.setBaseSize(QtCore.QSize(0, 0))
        self.clip_min.setObjectName("clip_min")
        self.horizontalLayout.addWidget(self.clip_min)
        self.clip_max = QtGui.QLineEdit(self.groupBox)
        self.clip_max.setObjectName("clip_max")
        self.horizontalLayout.addWidget(self.clip_max)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.y_num_ticks = QtGui.QLineEdit(self.groupBox)
        self.y_num_ticks.setObjectName("y_num_ticks")
        self.horizontalLayout_3.addWidget(self.y_num_ticks)
        self.y_resolution = QtGui.QLineEdit(self.groupBox)
        self.y_resolution.setObjectName("y_resolution")
        self.horizontalLayout_3.addWidget(self.y_resolution)
        self.formLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.x_num_ticks = QtGui.QLineEdit(self.groupBox)
        self.x_num_ticks.setObjectName("x_num_ticks")
        self.horizontalLayout_2.addWidget(self.x_num_ticks)
        self.x_resolution = QtGui.QLineEdit(self.groupBox)
        self.x_resolution.setObjectName("x_resolution")
        self.horizontalLayout_2.addWidget(self.x_resolution)
        self.formLayout.setLayout(7, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_8)
        self.x_tick_rotation = QtGui.QLineEdit(self.groupBox)
        self.x_tick_rotation.setObjectName("x_tick_rotation")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.x_tick_rotation)
        self.x_grid = QtGui.QCheckBox(self.groupBox)
        self.x_grid.setObjectName("x_grid")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.x_grid)
        self.y_grid = QtGui.QCheckBox(self.groupBox)
        self.y_grid.setObjectName("y_grid")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.y_grid)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.win_size = QtGui.QLineEdit(self.groupBox)
        self.win_size.setObjectName("win_size")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.win_size)
        self.verticalLayout.addLayout(self.formLayout)
        self.render = QtGui.QPushButton(self.groupBox)
        self.render.setObjectName("render")
        self.verticalLayout.addWidget(self.render)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(261, 87))
        self.groupBox_3.setMaximumSize(QtCore.QSize(261, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.freq_res = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freq_res.sizePolicy().hasHeightForWidth())
        self.freq_res.setSizePolicy(sizePolicy)
        self.freq_res.setReadOnly(True)
        self.freq_res.setObjectName("freq_res")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.freq_res)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.sampling_freq = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampling_freq.sizePolicy().hasHeightForWidth())
        self.sampling_freq.setSizePolicy(sizePolicy)
        self.sampling_freq.setReadOnly(True)
        self.sampling_freq.setObjectName("sampling_freq")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.sampling_freq)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.data_length = QtGui.QLineEdit(self.groupBox_3)
        self.data_length.setObjectName("data_length")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.data_length)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mpl = MplCanvas(self.groupBox_2)
        self.mpl.setObjectName("mpl")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.mpl)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_4.addWidget(self.mpl)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.downsample_fac, self.fft_size)
        MainWindow.setTabOrder(self.fft_size, self.overlap_fac)
        MainWindow.setTabOrder(self.overlap_fac, self.clip_min)
        MainWindow.setTabOrder(self.clip_min, self.clip_max)
        MainWindow.setTabOrder(self.clip_max, self.y_num_ticks)
        MainWindow.setTabOrder(self.y_num_ticks, self.y_resolution)
        MainWindow.setTabOrder(self.y_resolution, self.x_num_ticks)
        MainWindow.setTabOrder(self.x_num_ticks, self.x_resolution)
        MainWindow.setTabOrder(self.x_resolution, self.x_tick_rotation)
        MainWindow.setTabOrder(self.x_tick_rotation, self.x_grid)
        MainWindow.setTabOrder(self.x_grid, self.y_grid)
        MainWindow.setTabOrder(self.y_grid, self.render)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "SFFT Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Downsample Factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.downsample_fac.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.fft_size.setText(QtGui.QApplication.translate("MainWindow", "2**11", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Overlap Factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.overlap_fac.setText(QtGui.QApplication.translate("MainWindow", "0.9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Clip:", None, QtGui.QApplication.UnicodeUTF8))
        self.clip_min.setText(QtGui.QApplication.translate("MainWindow", "-60", None, QtGui.QApplication.UnicodeUTF8))
        self.clip_max.setText(QtGui.QApplication.translate("MainWindow", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Y Axis (Ticks, Resolution):", None, QtGui.QApplication.UnicodeUTF8))
        self.y_num_ticks.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.y_resolution.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "X Axis (Ticks, Resolution):", None, QtGui.QApplication.UnicodeUTF8))
        self.x_num_ticks.setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.x_resolution.setText(QtGui.QApplication.translate("MainWindow", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "X Tick Rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.x_tick_rotation.setText(QtGui.QApplication.translate("MainWindow", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.x_grid.setText(QtGui.QApplication.translate("MainWindow", "X Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.y_grid.setText(QtGui.QApplication.translate("MainWindow", "Y Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "FFT Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Win Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.win_size.setText(QtGui.QApplication.translate("MainWindow", "500", None, QtGui.QApplication.UnicodeUTF8))
        self.render.setText(QtGui.QApplication.translate("MainWindow", "Render", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Frequency Resolution [Hz]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Sampling Frequency [Hz]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Duration of input [s]:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Waterfall", None, QtGui.QApplication.UnicodeUTF8))

from mplcanvas import MplCanvas
